alg: ppo
bootstrap_count: 0
env: LunarLander-v2
eval_freq: 10000
frame_stack: null
log_folder: logs
lower: 0.0
max_resource: 6
min_delta: 0.05
min_resource: 4
n_envs: 1
n_evaluations: 5
n_jobs: 1
n_min_trials: 1
n_startup_trials: 5
n_timesteps: 20000
n_trials: 1
n_warmup_steps: 0
name: LunarLander-v2_ppo
patience: 50
percentile: 25.0
policy: MlpPolicy
#post_run: True
pruner: median
reduction_factor: 3.0
#reward_threshold: null
sampler: tpe
seed: 1
trial_log_path: logs/trials
upper: 1.0
