alg: ppo
bootstrap_count: 0
env: LunarLander-v2
eval_freq: 10000
frame_stack: null
log_folder: logs
lower: 0.0
max_resource: 6
metric:
  goal: maximize
  name: validation_loss
min_delta: 0.05
min_resource: 4
n_evaluations: 2
n_jobs: 1
n_min_trials: 1
n_startup_trials: 5
n_timesteps: 20000
n_trials: 500
n_warmup_steps: 0
name: study_22/02/2023_14:35:04
patience: 50
percentile: 25.0
policy: MlpPolicy
pruner: hyperband
reduction_factor: 3.0
sampler: tpe
seed: 1
upper: 1.0
